image:https://img.shields.io/packagist/l/doctrine/orm.svg?maxAge=2592000[]
image:https://travis-ci.org/redBorder/rbforwarder.svg?branch=master["Build Status", link="https://travis-ci.org/redBorder/rbforwarder"]
image:https://goreportcard.com/badge/github.com/redBorder/rbforwarder["Go Report", link=https://goreportcard.com/report/github.com/redBorder/rbforwarder]
image:https://coveralls.io/repos/github/redBorder/rbforwarder/badge.svg?branch=master["Coverage",link=https://coveralls.io/github/redBorder/rbforwarder?branch=master]
image:https://godoc.org/github.com/redBorder/rbforwarder?status.svg[link=https://godoc.org/github.com/redBorder/rbforwarder]

= rbforwarder

*rbforwarder* is a multi-protocol data forwarder. You can use it to forward data
between different protocols, for instance, creating a Kafka consumer to get
data from Kafka and use rbforwarder to send it to an HTTP endpoint.

The application also support decoding, encoding and processing data, for example
it can decode a JSON and performs modifications on it before send it encoded as
JSON again.

The application uses a pipeline with multiple workers to process data. It also
have a reporter to know if messages has been delivered successfully and can
retry messages on fail.

== Components

*Senders*

* MQTT
* HTTP
* Kafka

*Decoders / Encoders*

* JSON

*Processors*

- Template

== Road Map

|===
| Milestone | Feature | Status

| 0.1
| Backend
| _Beta_

| 0.2
| Report Handler
| _Beta_

| 0.4
| HTTP Sender
| _Beta_

| 0.5
| JSON encoder/decoder
| _Pending_

| 0.6
| JSON Template Processor
| _Pending_

| 0.7
| Kafka Producer
| _Pending_

| 0.8
| MQTT Publisher
| _Pending_

| 0.9
| InfluxDB metrics
| _Pending_

| 1.0
| Benchmarks
| _Pending_

|===
